services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: irrigation-system-app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - ../.env
    depends_on:
      - postgres
    volumes:
      - ..:/app
